# Generated by Django 5.0 on 2024-01-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposdecafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
