# Generated by Django 5.0 on 2024-01-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposdecafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='granos',
            name='altura_cultivo',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='granos',
            name='tiempo_cosecha',
            field=models.CharField(default=100, max_length=50),
        ),
        migrations.AddField(
            model_name='granos',
            name='tipo_semillas',
            field=models.CharField(default=100, max_length=50),
        ),
        migrations.AlterField(
            model_name='preparacion',
            name='tiempo',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
