# Generated by Django 5.0 on 2024-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposdecafe', '0002_granos_altura_cultivo_granos_tiempo_cosecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granos',
            name='altura_cultivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='granos',
            name='tiempo_cosecha',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='granos',
            name='tipo_semillas',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
