# Generated by Django 5.0 on 2024-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposdecafe', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='edad',
            field=models.IntegerField(default=18),
        ),
    ]
